### ISSUE TITLE
first

### ISSUE THREAD

**Issue by pranaygp** [webfreak7/cARdboard-ML#1]
If you're going to feature a 'bad example' on an article, it doesn't take too long till a bunch of people star it, thereby defeating the point of it being a 'bad example'.

Context: [https://medium.freecodecamp.com/how-we-got-a-2-year-old-repo-trending-on-github-in-just-48-hours-12151039d78b#.w4ti2e6rw]

Feel free to close(/delete?) this issue in favor of more important issues :)

**Comment by abhisuri97** [comment]
It's still at 1 star. i feel like my bad README has deterred people from looking at this lol.

but yeah ill close the issue 👍 

Also thanks for reading my article :)

**Comment by pranaygp** [comment]
2 stars now :)

Great article btw
